# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './MergeExcel2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(446, 352)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("border-color: rgb(72, 72, 72);")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 101, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 52, 101, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 102, 101, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 101, 20))
        self.label_4.setObjectName("label_4")
        self.textEdit_key = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_key.setGeometry(QtCore.QRect(20, 168, 81, 21))
        self.textEdit_key.setObjectName("textEdit_key")
        self.textBrowser_results = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_results.setGeometry(QtCore.QRect(150, 170, 261, 71))
        self.textBrowser_results.setObjectName("textBrowser_results")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 150, 101, 20))
        self.label_5.setObjectName("label_5")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(20, 200, 111, 16))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 220, 121, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton_merge = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_merge.setGeometry(QtCore.QRect(20, 250, 391, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_merge.setFont(font)
        self.pushButton_merge.setStyleSheet("background-color: rgb(144, 144, 144);\n"
"background-color: rgb(197, 197, 197);")
        self.pushButton_merge.setObjectName("pushButton_merge")
        self.pushButton_table1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_table1.setGeometry(QtCore.QRect(360, 70, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_table1.setFont(font)
        self.pushButton_table1.setStyleSheet("background-color: rgb(144, 144, 144);\n"
"background-color: rgb(197, 197, 197);")
        self.pushButton_table1.setObjectName("pushButton_table1")
        self.pushButton_table2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_table2.setGeometry(QtCore.QRect(360, 120, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_table2.setFont(font)
        self.pushButton_table2.setStyleSheet("background-color: rgb(144, 144, 144);\n"
"background-color: rgb(197, 197, 197);")
        self.pushButton_table2.setObjectName("pushButton_table2")
        self.textBrowser_table1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_table1.setGeometry(QtCore.QRect(20, 70, 331, 21))
        self.textBrowser_table1.setObjectName("textBrowser_table1")
        self.textBrowser_table2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_table2.setGeometry(QtCore.QRect(20, 120, 331, 21))
        self.textBrowser_table2.setObjectName("textBrowser_table2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(320, 280, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(10, 50, 411, 261))
        self.mdiArea.setObjectName("mdiArea")
        self.mdiArea.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.textEdit_key.raise_()
        self.textBrowser_results.raise_()
        self.label_5.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.pushButton_merge.raise_()
        self.pushButton_table1.raise_()
        self.pushButton_table2.raise_()
        self.textBrowser_table1.raise_()
        self.textBrowser_table2.raise_()
        self.label_7.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionRecent_Main_Image = QtWidgets.QAction(MainWindow)
        self.actionRecent_Main_Image.setObjectName("actionRecent_Main_Image")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionProjrctq = QtWidgets.QAction(MainWindow)
        self.actionProjrctq.setObjectName("actionProjrctq")
        self.actionProject2 = QtWidgets.QAction(MainWindow)
        self.actionProject2.setObjectName("actionProject2")
        self.actionAbout_Me = QtWidgets.QAction(MainWindow)
        self.actionAbout_Me.setObjectName("actionAbout_Me")
        self.actionContact_Me = QtWidgets.QAction(MainWindow)
        self.actionContact_Me.setObjectName("actionContact_Me")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionHistogram = QtWidgets.QAction(MainWindow)
        self.actionHistogram.setObjectName("actionHistogram")
        self.actionManual_Segmentation = QtWidgets.QAction(MainWindow)
        self.actionManual_Segmentation.setObjectName("actionManual_Segmentation")
        self.actionOTSU_Segmentation = QtWidgets.QAction(MainWindow)
        self.actionOTSU_Segmentation.setObjectName("actionOTSU_Segmentation")
        self.actionEntropy_Method_Segmentation = QtWidgets.QAction(MainWindow)
        self.actionEntropy_Method_Segmentation.setObjectName("actionEntropy_Method_Segmentation")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ExcelMerge"))
        self.label.setText(_translate("MainWindow", "Merge Tables"))
        self.label_2.setText(_translate("MainWindow", "Table 1 path"))
        self.label_3.setText(_translate("MainWindow", "Table 2 path"))
        self.label_4.setText(_translate("MainWindow", "Key name"))
        self.label_5.setText(_translate("MainWindow", "Results"))
        self.radioButton.setText(_translate("MainWindow", "Merge Pattern 1"))
        self.radioButton_2.setText(_translate("MainWindow", "Merge Pattern 2"))
        self.pushButton_merge.setText(_translate("MainWindow", "Begin to merge"))
        self.pushButton_table1.setText(_translate("MainWindow", "choose"))
        self.pushButton_table2.setText(_translate("MainWindow", "choose"))
        self.label_7.setText(_translate("MainWindow", "zhangjipinggom@163.com"))
        self.actionOpen.setText(_translate("MainWindow", "Open Main Image"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionRecent_Main_Image.setText(_translate("MainWindow", "Recent Main Image"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionProjrctq.setText(_translate("MainWindow", "Projrct1"))
        self.actionProject2.setText(_translate("MainWindow", "Project2"))
        self.actionAbout_Me.setText(_translate("MainWindow", "About Me"))
        self.actionContact_Me.setText(_translate("MainWindow", "Contact Me"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionHistogram.setText(_translate("MainWindow", "Histogram"))
        self.actionManual_Segmentation.setText(_translate("MainWindow", "Manual Segmentation"))
        self.actionOTSU_Segmentation.setText(_translate("MainWindow", "OTSU Segmentation"))
        self.actionEntropy_Method_Segmentation.setText(_translate("MainWindow", "Entropy Method Segmentation"))

